name: release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name:    publish
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: set up Node for npm
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: install dependencies
        run:  npm ci

      - name: build
        run:  npm run build --if-present

      - name: run tests
        run:  npm test --if-present

      - name: publish to npm
        run:  npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: set up Node for GitHub
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com
          scope:        '@digitallinguistics'

      - name: publish to GitHub Package Registry
        run:  npm publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}